// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcgibxksrrrggzgredst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZ2lieGtzcnJyZ2d6Z3JlZHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODI4MzQsImV4cCI6MjA2MTg1ODgzNH0.8uVJDs3r3MazEZOQkU5AKxFIu5OuFhCmy6TDuA-H1qg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);